name: FixedPhrasePlugin
version: ${project.version}
main: com.gmail.tonatumi.fixedphraseplugin.FixedPhrasePlugin
commands:
  fpp:
    description: open Fixed Phrase GUI
    usage: /<command>
    default: true