name: FixedPhrasePlugin
version: ${project.version}
main: com.gmail.tonatumi.fixedphraseplugin.FixedPhrasePlugin
command:
  fpp:
    description: fpp で定型文リストを開きます。
    usage: /<command>
    default: true